migit: Implement safety checks for GIT_SOURCE_URL against script directory
This commit enhances the script's safety by implementing checks to ensure that the GIT_SOURCE_URL does not point to the script's own directory or its subdirectories. These checks involve:

- Determining the absolute path of the current script.
- Extracting and normalizing the absolute path from GIT_SOURCE_URL,
  considering various formats including 'file://', absolute paths,
  and relative paths starting with './'.
- Preventing the execution if GIT_SOURCE_URL is within the script's
  directory or its subdirectories, which is crucial to avoid unintended
  manipulations of the script's repository or associated files.

This addition significantly increases the robustness of the script.

diff --git a/migit b/migit
--- a/migit
+++ b/migit
@@ -254,21 +254,57 @@ fi
 if [[ -z "$GIT_SOURCE_URL" ]]; then
 	echo "Clone URL was not specified."
 	show_help
-	exit 1
+	if [[ "$NO_PROGRESS" == "$TRUE" ]]; then
+		exit 1
+	else
+		exit 0 # only if the script is used in quiet mode within automation, e.g. in cron jobs
+	fi
 elif [[ "$GIT_SOURCE_URL" == file:* ]]; then
-	echo "Invalid protocol: 'file://' is not allowed. Please use a relative path for local access."
-	exit 1
+	echo "Invalid protocol: 'file://' is not allowed. Please use a relative path to a valid git repository for local access."
+		if [[ "$NO_PROGRESS" == "$TRUE" ]]; then
+		exit 1
+	else
+		exit 0 # only if the script is used in quiet mode within automation, e.g. in cron jobs
+	fi
 fi
 
-# Create deploy directory
+# get absolute path of the current script
+SCRIPT_DIR=$(realpath $(dirname "$0"))
+
+# Extract the absolute path from GIT_SOURCE_URL if it's a local path
+if [[ "$GIT_SOURCE_URL" == file://* ]]; then
+	# Removes 'file://' and converts to an absolute path, this is already handled, but here only for completeness
+	GIT_REPO_PATH=$(realpath "${GIT_SOURCE_URL:7}")
+elif [[ "$GIT_SOURCE_URL" == /* ]]; then
+	# Converts to an absolute path
+	GIT_REPO_PATH=$(realpath "$GIT_SOURCE_URL")
+elif [[ "$GIT_SOURCE_URL" == ./* || "$GIT_SOURCE_URL" == ./ ]]; then
+	# Converts to an absolute path, if `./` or a path within it is used
+	GIT_REPO_PATH=$(realpath "$GIT_SOURCE_URL")
+else
+	# Sets the path to empty if it's not a local file URL
+	GIT_REPO_PATH=""
+fi
+
+# Check if GIT_REPO_PATH is within SCRIPT_DIR
+if [[ "$GIT_REPO_PATH" == "$SCRIPT_DIR"* ]]; then
+	echo "Error: The specified git URL ('$GIT_SOURCE_URL') is located within the script's directory or its subdirectories. Please specify a different URL."
+	if [[ "$NO_PROGRESS" == "$TRUE" ]]; then
+		exit 1
+	else
+		exit 0 # only if the script is used in quiet mode within automation, e.g. in cron jobs
+	fi
+fi
+
+## Create deploy directory
 mkdir -p $DEPLOY_DIR
 
-# Get the original repository, delete it if already exists, it must be fresh
+## Get the original repository, delete it if already exists, it must be fresh
 if [ -d $GIT_TEMP_REPO/.git ]; then
 	rm -rf $GIT_TEMP_REPO 
 fi
 
-# Function to replace the echo command, for usage with the -q optiom
+## Function to replace the echo command, for usage with the -q optiom
 function my_echo() {
 	if [ "$NO_PROGRESS" == "$FALSE" ]; then
 		echo "${@}"
@@ -277,7 +313,7 @@ function my_echo() {
 	fi
 }
 
-# Function to display a spinner while a process is running
+## Function to display a spinner while a process is running
 function show_spinner() {
 	local pid="$1"
 	local message="$2"
